# Copyright 2022 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# To run the Cloud Build workflow, execute the following from the root
# directory:
# gcloud builds submit --config=debian_worker_cloudbuild.yaml .

timeout: 4500s

substitutions:
  _BUILDER_PROJECT: 'compute-image-import-test'

steps:
- id: 'build-e2e-test-base'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-f','e2e_test_base.Dockerfile',
         '-t','gcr.io/$_BUILDER_PROJECT/e2e-test-base:ks-test',
         '.',]
- id: 'push-e2e-test-base'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$_BUILDER_PROJECT/e2e-test-base:ks-test']
- id: 'build-gce_image_import_export_tests'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-f','gce_image_import_export_tests.Dockerfile',
         '-t','gcr.io/$_BUILDER_PROJECT/e2e:ks-test',
         '--build-arg=PROJECT_ID=$_BUILDER_PROJECT',
         '.',]
- id: 'push-gce_image_import_export_tests'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$_BUILDER_PROJECT/e2e:ks-test']

- id: run-e2e-tests
  name: 'gcr.io/$_BUILDER_PROJECT/e2e:ks-test'
  entrypoint: '/bin/sh'
  args: 
    - '-c'
    - |
      cd /
      ./gce_image_import_export_test_runner \
      -test_project_id=${_BUILDER_PROJECT} \
      -test_zone=us-central1-a \
      -test_suite_filter=^ImageImport$ \
      -test_case_filter=rhel-8

#- id: gce-image-import-export-tests
#  name: 'gcr.io/kaniko-project/executor:v0.22.0'
#  args:
#  - --destination=gcr.io/$_BUILDER_PROJECT/gce-image-import-export-tests:latest
#  - --destination=gcr.io/$_BUILDER_PROJECT/gce-image-import-export-tests:$COMMIT_SHA
#  - --context=/workspace
#  - --dockerfile=gce_image_import_export_tests.Dockerfile
#  - --build-arg=PROJECT_ID=$_BUILDER_PROJECT
#  - --build-arg=test_suite_filter=^ImageImport$
#  - --build-arg=test_case_filter=rhel-8
